version: 2
updates:
  - package-ecosystem: npm
    directory: "/packages/babel/"
    schedule:
      interval: daily
    target-branch: develop
    versioning-strategy: lockfile-only

  - package-ecosystem: npm
    directory: "/packages/cli/"
    schedule:
      interval: daily
    target-branch: develop
    versioning-strategy: lockfile-only

  - package-ecosystem: npm
    directory: "/packages/unplugin/"
    schedule:
      interval: daily
    target-branch: develop
    versioning-strategy: lockfile-only
