[package]
name = "import-meta-env"
version = "0.1.5"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.0", features = ["derive"] }
anyhow = "1.0"
glob = "0.3.0"
dotenv = "0.15.0"
serde_json = "1.0.79"
regex = "1"

[dev-dependencies]
assert_cmd = "2.0"
assert_fs = "1.0"
predicates = "2.1"
insta = "1.13.0"
