name: CI

on:
  push:
  pull_request:

jobs:
  lts:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            node_version: 16
      fail-fast: false
    name: "lts: ${{ matrix.os }}, node@${{ matrix.node_version }}, ${{ matrix.os }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ^6

      - name: Set node version to ${{ matrix.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
          cache: "pnpm"

      - name: Install deps
        run: pnpm i

      - name: Test
        run: pnpm run test --parallel --stream --filter @import-meta-env/*

      - name: Build
        run: pnpm run build --parallel --stream --filter @import-meta-env/*

      - name: Install binary
        run: pnpm i

      - name: Build&Test examples
        run: |
          pnpm \
            --parallel \
            --stream \
            --filter *-example \
            --filter \!vite-html-example \
            --filter \!vite-vue-* \
            exec sh test.sh

      - name: Build&Test examples/vite-vue-*
        if: ${{ matrix.node_version >= '14' }}
        run: |
          pnpm \
            --parallel \
            --stream \
            --filter vite-vue* \
            exec sh test.sh

  compatibility:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [12, 14, 16, 17]
        dotenv_version: [8, 9, 10, 11, 12, 13, 14, 15, 16]
        include:
          - os: macos-latest
            node_version: lts/*
            dotenv_version: latest
          - os: windows-latest
            node_version: lts/*
            dotenv_version: latest
      fail-fast: false
    name: "compatibility: ${{ matrix.os }}, dotenv@${{ matrix.dotenv_version }}, node@${{ matrix.node_version }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ^6

      - name: Set node version to ${{ matrix.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
          cache: "pnpm"

      - name: Install package
        run: |
          pnpm i
          pnpm --parallel --stream --filter @import-meta-env/* exec pnpm rm dotenv
          pnpm --parallel --stream --filter @import-meta-env/* exec pnpm i --save-peer dotenv@${{ matrix.dotenv_version }}

      - name: Test package
        run: pnpm run test --parallel --stream --filter @import-meta-env/*

      - name: Build package
        run: pnpm run build --parallel --stream --filter @import-meta-env/*

      - name: Install binary
        run: pnpm i --no-frozen-lockfile

      - name: Test example
        run: pnpm run test --parallel --stream --filter vite-html-example

  lint:
    runs-on: ubuntu-latest
    name: "lint"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6

      - name: Set node version to 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "pnpm"

      - name: Install deps
        run: pnpm install

      - name: Check formatting
        run: pnpm prettier --check .
